### ISSUE TITLE
TF module examples refers to old versions of module

### ISSUE THREAD

**Issue by vikas-karadia** [Gravitas-Security/Cloudflare-Modules#53]
The examples provided  https://github.com/Gravitas-Security/Cloudflare-Modules/blob/v2.5.3/example/zone/dns.tf#L2 refers to old version on module. Can they be updates with the latest version 2.5.3?

**Comment by vikas-karadia** [comment]
@CyberViking949

**Comment by CyberViking949** [comment]
updated examples to use new versions, as well as the new structure to take advantage of new features

https://github.com/Gravitas-Security/Cloudflare-Modules/pull/56
